#!/bin/bash
# Script for start multi Agents for multi Redis instances on one machchine.
#
# Each redis instance should have one agent.
# Redis instances on one machine have the same ip addr but different ports. 
# Config the variables below then start the script.

ped=`pwd`
case $1 in
start)
	cd /data/follower/local/zookeeper/zookeeper-3.4.3 && bin/zkServer.sh start
	;;
stop)
	cd /data/follower/local/zookeeper/zookeeper-3.4.3 && bin/zkServer.sh stop
	;;
connect)
	cd /data/follower/local/zookeeper/zookeeper-3.4.3 && bin/zkCli.sh -server 10.22.241.233:8181
	;;
online)
        cd /data/follower/local/zookeeper/zookeeper-3.4.3 && bin/zkCli.sh -server webzk4.d.xiaonei.com:2181,webzk5.d.xiaonei.com:2181
        ;;
*)
	echo -e "Usage: $0 {start|stop|connect|online}" >&2
esac
cd $ped
