#!/bin/bash

times=`date +"%Y%m%d_%H%M%S"`

bugid=`pwd`
bugid=${bugid//^/ }
bugid=${bugid//-/ }
bugid=`echo $bugid | rev | cut -d ' ' -f 1 | rev`

if grep '^[[:digit:]]*$' <<< "$bugid" > /dev/null
then
  echo "@ The interpreted BUG ID: $bugid"
else
  if [ $# -lt 1 ]
  then
    echo "Can not interpret BUG ID, Please enter it from command line."
    exit 1
  else
    bugid=$1
  fi
fi

filename="$bugid-$times.patch"

echo "@ svn diff >$filename"
svn diff >$filename || echo "    Failed to generate patch file, exit..." && exit 2
head $filename

echo "@ copy file to remote server."
scp $filename *.creview lex@10.99.116.66:~/workbackup/

echo "Done."