#!/bin/sh
# Copy file or dir to remote server by SCP command.

[ $# -lt 2 ] && {
  echo "Usage: `basename $0` <server number> [-r dir] or [file]"
  exit -1
}
dir=`pwd`
HA="~"
dir=${dir/$HOME/$HA}
echo "SCP to remote - "$dir
name=$1
shift
case $name in
52l)
        scp $* lex@10.34.130.52:$dir
        sst=$?
        ;;
52x)
        scp $* xiejiyun@10.34.130.52:$dir
        sst=$?
        ;;
521)
        scp $* lex1@10.34.130.52:$dir
        sst=$?
        ;;
522)
        scp $* lex2@10.34.130.52:$dir
        sst=$?
        sst=$?
        ;;
523)
        scp $* lex3@10.34.130.52:$dir
        sst=$?
        ;;
53l)
        scp $* lex@10.34.130.53:$dir
        sst=$?
        ;;
53x)
        scp $* xiejiyun@10.34.130.53:$dir
        sst=$?
        ;;
66l)
        scp $* lex@10.99.116.66:$dir
        sst=$?
        ;;
66x)
        scp $* xiejiyun@10.99.116.66:$dir
        sst=$?
        ;;
68l)
        scp $* lex@10.99.116.68:$dir
        sst=$?
        ;;
67l)
        scp $* lex@10.99.116.67:$dir
        sst=$?
        ;;
*)
        echo -e "Usage: $0 {66|67|68}" >&2
        exit -1
esac
echo "SCP status: $sst && $?"